sudo: false
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
language: bash
before_install:
- mkdir $HOME/bin
- curl -o $HOME/bin/bashtub https://raw.githubusercontent.com/ueokande/bashtub/master/bin/bashtub
- chmod +x $HOME/bin/bashtub
- export PATH="$HOME/bin:$PATH"
script:
- git ls-files usr/ profile | xargs shellcheck
- bashtub `find test -name '*_test.sh'`
